apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stress-network-policy-{{.Iteration}}
spec:
  podSelector:
    matchLabels:
      stress-type: network-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          stress-type: network-client
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          stress-type: network-client