apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-cpu-mem-{{.deploymentType}}-{{.Iteration}}-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-cpu-mem-{{.deploymentType}}-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: stress-cpu-mem-{{.deploymentType}}-{{.Iteration}}-{{.Replica}}
        stress-type: cpu-mem
        deployment-type: "{{.deploymentType}}"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: stress-cpu-mem
        image: quay.io/jparrill/kube-burner-stress-tools:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            stress-ng {{.stressArgs}}
        resources:
          requests:
            memory: "{{.memoryRequest}}"
            cpu: "{{.cpuRequest}}"
          limits:
            memory: "{{.memoryLimit}}"
            cpu: "{{.cpuLimit}}"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault