kind: Pod
apiVersion: v1
metadata:
  name: kubelet-density-{{.Iteration}}-{{.Replica}}
  labels:
    name: kubelet-density
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: kubelet-density
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
