apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-net-server-{{.Iteration}}-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-net-server-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: stress-net-server-{{.Iteration}}-{{.Replica}}
        stress-type: network-server
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: stress-net-server
        image: quay.io/jparrill/kube-burner-stress-tools:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            # Simple HTTP server using netcat
            while true; do
              echo -e "HTTP/1.1 200 OK\r\nContent-Length: 50\r\n\r\nNetwork stress test server running on {{.serverPort}}" | nc -l -p {{.serverPort}}
            done
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "{{.serverPort}}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
